/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ParcelRouteImport } from './routes/parcel'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as TrackBookingRouteImport } from './routes/track-booking'
import { Route as TrackParcelRouteImport } from './routes/track-parcel'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelRoute = ParcelRouteImport.update({
  id: '/parcel',
  path: '/parcel',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackBookingRoute = TrackBookingRouteImport.update({
  id: '/track-booking',
  path: '/track-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackParcelRoute = TrackParcelRouteImport.update({
  id: '/track-parcel',
  path: '/track-parcel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/parcel': typeof ParcelRoute
  '/routes': typeof RoutesRoute
  '/track-booking': typeof TrackBookingRoute
  '/track-parcel': typeof TrackParcelRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/parcel': typeof ParcelRoute
  '/routes': typeof RoutesRoute
  '/track-booking': typeof TrackBookingRoute
  '/track-parcel': typeof TrackParcelRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/parcel': typeof ParcelRoute
  '/routes': typeof RoutesRoute
  '/track-booking': typeof TrackBookingRoute
  '/track-parcel': typeof TrackParcelRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/contact'
    | '/parcel'
    | '/routes'
    | '/track-booking'
    | '/track-parcel'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/contact'
    | '/parcel'
    | '/routes'
    | '/track-booking'
    | '/track-parcel'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/contact'
    | '/parcel'
    | '/routes'
    | '/track-booking'
    | '/track-parcel'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  ParcelRoute: typeof ParcelRoute
  RoutesRoute: typeof RoutesRoute
  TrackBookingRoute: typeof TrackBookingRoute
  TrackParcelRoute: typeof TrackParcelRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcel': {
      id: '/parcel'
      path: '/parcel'
      fullPath: '/parcel'
      preLoaderRoute: typeof ParcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-booking': {
      id: '/track-booking'
      path: '/track-booking'
      fullPath: '/track-booking'
      preLoaderRoute: typeof TrackBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-parcel': {
      id: '/track-parcel'
      path: '/track-parcel'
      fullPath: '/track-parcel'
      preLoaderRoute: typeof TrackParcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  ParcelRoute: ParcelRoute,
  RoutesRoute: RoutesRoute,
  TrackBookingRoute: TrackBookingRoute,
  TrackParcelRoute: TrackParcelRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
